
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1724:Type names should not match namespaces", Justification = "We should not keep track with naming schemes of external libraries.", Scope = "type", Target = "~T:ShapeDatabase.Util.Functions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Improves readability.", Scope = "member", Target = "~F:ShapeDatabase.IO.IOConventions.NORMALISED_DATA")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Library' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Shapes.IMeshLibrary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Library' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Shapes.MeshLibrary")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.IRecordHolder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.IRecordHolder`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.ICachedRecordHolder`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.RecordHolder`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.CachedRecordHolder`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.DirectRecordHolder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'Record' is an English word which already identifies the collection of variables.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.Record")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'List' is an English word which already identifies the collection of variables", Scope = "type", Target = "~T:ShapeDatabase.Util.Collections.SortedList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "A 'List' is an English word which already identifies the collection of variables", Scope = "type", Target = "~T:ShapeDatabase.Util.Collections.ConcurrentSortedList`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "The C in the name is an abreviation for Collection.", Scope = "type", Target = "~T:ShapeDatabase.Util.Collections.ArrayWC`1")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1724:Type names should not match namespaces", Justification = "This class is not used together with the System.Net namespace.", Scope = "type", Target = "~T:ShapeDatabase.Features.Statistics.Cache`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Keyword can be used because of capitalisation.", Scope = "member", Target = "~P:ShapeDatabase.Shapes.IMeshEntry.Class")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Changing this location helps improve query performance.", Scope = "member", Target = "~P:ShapeDatabase.IO.FileManager.ProcessedMeshes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Changing this location helps improve query performance.", Scope = "member", Target = "~P:ShapeDatabase.IO.FileManager.QueryMeshes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Changing this location helps improve query performance.", Scope = "member", Target = "~P:ShapeDatabase.Shapes.LibraryManager.ProcessedMeshes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Changing this location helps improve query performance.", Scope = "member", Target = "~P:ShapeDatabase.Shapes.LibraryManager.QueryMeshes")]
