//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShapeDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShapeDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string D_ContentDir {
            get {
                return ResourceManager.GetString("D_ContentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluations.csv.
        /// </summary>
        internal static string D_EvaluationFile {
            get {
                return ResourceManager.GetString("D_EvaluationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string D_FailedDir {
            get {
                return ResourceManager.GetString("D_FailedDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectors.
        /// </summary>
        internal static string D_FeatureDir {
            get {
                return ResourceManager.GetString("D_FeatureDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featurevectors.csv.
        /// </summary>
        internal static string D_FeatureFile {
            get {
                return ResourceManager.GetString("D_FeatureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        internal static string D_FinalDir {
            get {
                return ResourceManager.GetString("D_FinalDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial.
        /// </summary>
        internal static string D_InitialDir {
            get {
                return ResourceManager.GetString("D_InitialDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string D_MeasureDir {
            get {
                return ResourceManager.GetString("D_MeasureDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measures.csv.
        /// </summary>
        internal static string D_MeasureFile {
            get {
                return ResourceManager.GetString("D_MeasureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string D_QueryDir {
            get {
                return ResourceManager.GetString("D_QueryDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queryresults.csv.
        /// </summary>
        internal static string D_QueryFile {
            get {
                return ResourceManager.GetString("D_QueryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.ini.
        /// </summary>
        internal static string D_SettingsFile {
            get {
                return ResourceManager.GetString("D_SettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        internal static string D_ShapesDir {
            get {
                return ResourceManager.GetString("D_ShapesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        internal static string D_TempDir {
            get {
                return ResourceManager.GetString("D_TempDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not cast an object of type {0} to type {1}..
        /// </summary>
        internal static string EX_Cast {
            get {
                return ResourceManager.GetString("EX_Cast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided directory does not exist &apos;{0}&apos;..
        /// </summary>
        internal static string EX_Directoy_NotExist {
            get {
                return ResourceManager.GetString("EX_Directoy_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current record already contains a snapshot. Please reset the RecordHolder first before taking another snapshot..
        /// </summary>
        internal static string EX_Dubble_Snapshot {
            get {
                return ResourceManager.GetString("EX_Dubble_Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is empty, this method does not accept arrays without values..
        /// </summary>
        internal static string EX_Empty_Array {
            get {
                return ResourceManager.GetString("EX_Empty_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read data from the end of a stream..
        /// </summary>
        internal static string EX_EndOfStream {
            get {
                return ResourceManager.GetString("EX_EndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided number had a negative value while this function only excepts positive values. Given value {0}..
        /// </summary>
        internal static string EX_ExpPosValue {
            get {
                return ResourceManager.GetString("EX_ExpPosValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load file &apos;{0}&apos; because it does not exist..
        /// </summary>
        internal static string EX_FileNotFound {
            get {
                return ResourceManager.GetString("EX_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load file &apos;{0}&apos; because of an Exception..
        /// </summary>
        internal static string EX_FileNotLoad {
            get {
                return ResourceManager.GetString("EX_FileNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use the constructor without IOWriteResult variables..
        /// </summary>
        internal static string EX_G3_Writer {
            get {
                return ResourceManager.GetString("EX_G3_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current class cannot read &apos;{0}&apos;, expected format(s) &apos;{1}&apos;..
        /// </summary>
        internal static string EX_Invalid_Format {
            get {
                return ResourceManager.GetString("EX_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided format could not be processed by this class..
        /// </summary>
        internal static string EX_Invalid_Format_No_Args {
            get {
                return ResourceManager.GetString("EX_Invalid_Format_No_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vector size, expected size {0} but got &apos;{1}&apos;.
        /// </summary>
        internal static string EX_Invalid_Vector_Size {
            get {
                return ResourceManager.GetString("EX_Invalid_Vector_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided maximum value is below the minimum bound. The maximum value should always be larger than this minimum bound..
        /// </summary>
        internal static string EX_MinMax_Switch {
            get {
                return ResourceManager.GetString("EX_MinMax_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extension where provided for reader &apos;{0}&apos;. Add your own reader to the FileManager by using the AddReader(IReader&lt;&gt;) method..
        /// </summary>
        internal static string EX_Missing_Ext {
            get {
                return ResourceManager.GetString("EX_Missing_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations for the given data is currently not supported: {0}.
        /// </summary>
        internal static string EX_Not_Supported {
            get {
                return ResourceManager.GetString("EX_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided arrays do not have the same size, all should be of the same length. Expected Size: {0}, Given Size {1}..
        /// </summary>
        internal static string EX_UnEqual_Sizes {
            get {
                return ResourceManager.GetString("EX_UnEqual_Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeshName.
        /// </summary>
        internal static string F_MeshName {
            get {
                return ResourceManager.GetString("F_MeshName", resourceCulture);
            }
        }
    }
}
