//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShapeDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShapeDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia Retrieval - K. Westerbaan &amp; G. de Jonge.
        /// </summary>
        internal static string A_WindowName {
            get {
                return ResourceManager.GetString("A_WindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd-HH-mm-ss.
        /// </summary>
        internal static string F_DateFormat {
            get {
                return ResourceManager.GetString("F_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}.
        /// </summary>
        internal static string F_File_Features {
            get {
                return ResourceManager.GetString("F_File_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}.
        /// </summary>
        internal static string F_File_Measure {
            get {
                return ResourceManager.GetString("F_File_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished cleaning directories!.
        /// </summary>
        internal static string I_EndClean {
            get {
                return ResourceManager.GetString("I_EndClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done loading meshes..
        /// </summary>
        internal static string I_EndLoad_Mesh {
            get {
                return ResourceManager.GetString("I_EndLoad_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done measuring meshes..
        /// </summary>
        internal static string I_EndMeasure {
            get {
                return ResourceManager.GetString("I_EndMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done extracting descriptors..
        /// </summary>
        internal static string I_EndProc_Feature {
            get {
                return ResourceManager.GetString("I_EndProc_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done converting input!.
        /// </summary>
        internal static string I_EndProc_Input {
            get {
                return ResourceManager.GetString("I_EndProc_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done processing meshes..
        /// </summary>
        internal static string I_EndProc_Mesh {
            get {
                return ResourceManager.GetString("I_EndProc_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to exit the application..
        /// </summary>
        internal static string I_ExitPropmt {
            get {
                return ResourceManager.GetString("I_ExitPropmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureVectors exported to: {0}.
        /// </summary>
        internal static string I_Feature_Exp {
            get {
                return ResourceManager.GetString("I_Feature_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureVectors imported from: {0}.
        /// </summary>
        internal static string I_Feature_Imp {
            get {
                return ResourceManager.GetString("I_Feature_Imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics exported to: {0}.
        /// </summary>
        internal static string I_Measure_Exp {
            get {
                return ResourceManager.GetString("I_Measure_Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shapes are available:.
        /// </summary>
        internal static string I_ShapeCount {
            get {
                return ResourceManager.GetString("I_ShapeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a shape, or write down {0} to exit the program..
        /// </summary>
        internal static string I_ShapeSelect_Prompt {
            get {
                return ResourceManager.GetString("I_ShapeSelect_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning directories!.
        /// </summary>
        internal static string I_StartClean {
            get {
                return ResourceManager.GetString("I_StartClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start loading meshes..
        /// </summary>
        internal static string I_StartLoad_Mesh {
            get {
                return ResourceManager.GetString("I_StartLoad_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start measuring meshes..
        /// </summary>
        internal static string I_StartMeasure {
            get {
                return ResourceManager.GetString("I_StartMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start extracting descriptors..
        /// </summary>
        internal static string I_StartProc_Feature {
            get {
                return ResourceManager.GetString("I_StartProc_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting converting input!.
        /// </summary>
        internal static string I_StartProc_Input {
            get {
                return ResourceManager.GetString("I_StartProc_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start processing meshes..
        /// </summary>
        internal static string I_StartProc_Mesh {
            get {
                return ResourceManager.GetString("I_StartProc_Mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startin Up!.
        /// </summary>
        internal static string I_StartUp {
            get {
                return ResourceManager.GetString("I_StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string I_UnknownCommand {
            get {
                return ResourceManager.GetString("I_UnknownCommand", resourceCulture);
            }
        }
    }
}
